# Requires Docker Compose 1.19+ and nvidia-docker2.
version: '2.3'
services:
  main:
    build: .
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/hostname:/etc/hostname:ro
    environment:
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - DISPLAY
      - PYTHONIOENCODING=utf_8
    init: true
    runtime: nvidia
    ipc: host
    network_mode: host
